# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Keon/Dropbox/Senior_Design_3/Senior_Design_Built_In_FIFO/Senior_Design_Built_In_FIFO.srcs/sources_1/ip/bram_fifo_1/bram_fifo.xci
# IP: The module: 'bram_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Keon/Dropbox/Senior_Design_3/Senior_Design_Built_In_FIFO/Senior_Design_Built_In_FIFO.srcs/sources_1/ip/bram_fifo_1/bram_fifo/bram_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Keon/Dropbox/Senior_Design_3/Senior_Design_Built_In_FIFO/Senior_Design_Built_In_FIFO.srcs/sources_1/ip/bram_fifo_1/bram_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Keon/Dropbox/Senior_Design_3/Senior_Design_Built_In_FIFO/Senior_Design_Built_In_FIFO.srcs/sources_1/ip/bram_fifo_1/bram_fifo.xci
# IP: The module: 'bram_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Keon/Dropbox/Senior_Design_3/Senior_Design_Built_In_FIFO/Senior_Design_Built_In_FIFO.srcs/sources_1/ip/bram_fifo_1/bram_fifo/bram_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Keon/Dropbox/Senior_Design_3/Senior_Design_Built_In_FIFO/Senior_Design_Built_In_FIFO.srcs/sources_1/ip/bram_fifo_1/bram_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
